import type { CSSProperties } from "react";

export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: { marginBottom: 20 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 16px",
    borderRadius: 8,
    background: "var(--warn-bg, var(--bg-surface))",
    border: "1px solid var(--border)",
    marginBottom: 16,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  split: { display: "flex", gap: 20, minHeight: 400 } satisfies CSSProperties,
  listCol: {
    width: 320,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    textAlign: "left",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    cursor: "pointer",
  } satisfies CSSProperties,
  rowActive: {
    border: "1px solid var(--accent)",
    background: "var(--accent-muted)",
  } satisfies CSSProperties,
  rowTop: { display: "flex", alignItems: "center", gap: 8, width: "100%" } satisfies CSSProperties,
  path: {
    flex: 1,
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  badge: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    padding: "2px 7px",
    borderRadius: 4,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    flexShrink: 0,
  } satisfies CSSProperties,
  usedBy: {
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  detailCol: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: 24,
  } satisfies CSSProperties,
  detailHeader: { display: "flex", alignItems: "center", gap: 10, marginBottom: 16, flexWrap: "wrap" } satisfies CSSProperties,
  detailPath: { fontSize: 15, fontWeight: 600, fontFamily: "var(--font-mono, monospace)" } satisfies CSSProperties,
  noPreview: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
