import type { CSSProperties } from "react";

export const s = {
  page: { padding: "24px 32px 44px", maxWidth: 1100, margin: "0 auto" } satisfies CSSProperties,
  header: { marginBottom: 20 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", marginTop: 4 } satisfies CSSProperties,
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 16px",
    borderRadius: 8,
    background: "var(--warn-bg, var(--bg-surface))",
    border: "1px solid var(--border)",
    marginBottom: 16,
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  split: { display: "flex", gap: 20, minHeight: 400, alignItems: "flex-start" } satisfies CSSProperties,
  listCol: {
    width: 320,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 6,
    maxHeight: "calc(100vh - 220px)",
    overflowY: "auto",
    paddingRight: 4,
  } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "flex-start",
    flexDirection: "column",
    gap: 6,
    width: "100%",
    textAlign: "left",
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    cursor: "pointer",
  } satisfies CSSProperties,
  rowActive: {
    border: "1px solid var(--accent)",
    background: "var(--accent-muted)",
  } satisfies CSSProperties,
  rowTop: { display: "flex", alignItems: "center", gap: 8, width: "100%" } satisfies CSSProperties,
  path: {
    flex: 1,
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  badge: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "var(--bg-hover)",
    padding: "2px 7px",
    borderRadius: 4,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    flexShrink: 0,
  } satisfies CSSProperties,
  usedBy: {
    fontSize: 12,
    color: "var(--text-muted)",
    display: "flex",
    alignItems: "center",
    gap: 5,
  } satisfies CSSProperties,
  detailCol: {
    flex: 1,
    minWidth: 0,
    borderRadius: 10,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    padding: 24,
    maxHeight: "calc(100vh - 220px)",
    overflowY: "auto",
  } satisfies CSSProperties,
  detailHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
    paddingBottom: 14,
    borderBottom: "1px solid var(--border)",
    flexWrap: "wrap",
    position: "sticky",
    top: -24,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  detailPath: { fontSize: 15, fontWeight: 600, fontFamily: "var(--font-mono, monospace)", flex: 1, minWidth: 0, overflow: "hidden", textOverflow: "ellipsis" } satisfies CSSProperties,
  detailBody: { fontSize: 14, lineHeight: 1.6, color: "var(--text-secondary)" } satisfies CSSProperties,
  noPreview: { fontSize: 13, color: "var(--text-muted)" } satisfies CSSProperties,

  // ---- Toolbar (SPEC-02) ----
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
    marginBottom: 14,
    paddingBottom: 14,
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,
  toolbarSpacer: { flex: 1 } satisfies CSSProperties,
  rootLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    color: "var(--text-muted)",
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  rootPill: {
    padding: "2px 7px",
    borderRadius: 4,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  rootPillActive: {
    color: "var(--text-primary)",
    background: "var(--accent-muted)",
    border: "1px solid var(--accent)",
  } satisfies CSSProperties,
  inlineForm: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    marginBottom: 14,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  inlineInput: {
    flex: 1,
    fontSize: 13,
    fontFamily: "var(--font-mono, monospace)",
    padding: "6px 9px",
    borderRadius: 6,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-input, var(--bg-surface))",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  inlineError: { fontSize: 12, color: "var(--crit)", marginTop: 6 } satisfies CSSProperties,
  visuallyHidden: {
    position: "absolute",
    width: 1,
    height: 1,
    padding: 0,
    margin: -1,
    overflow: "hidden",
    clip: "rect(0,0,0,0)",
    border: 0,
  } satisfies CSSProperties,

  // ---- Preview | Edit (SPEC-02) ----
  modeRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    marginLeft: "auto",
  } satisfies CSSProperties,
  editorWrap: { display: "flex", flexDirection: "column", gap: 10 } satisfies CSSProperties,
  textarea: {
    width: "100%",
    minHeight: 320,
    resize: "vertical",
    fontSize: 13,
    lineHeight: 1.6,
    fontFamily: "var(--font-mono, monospace)",
    padding: 12,
    borderRadius: 8,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-input, var(--bg-surface))",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  saveRow: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  saveHint: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
  conflictBanner: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 8,
    background: "var(--warn-bg, var(--bg-surface))",
    border: "1px solid var(--warn, var(--border-strong))",
    fontSize: 13,
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  conflictActions: { display: "flex", gap: 8 } satisfies CSSProperties,
} as const;
