import type { CiExportInput, CiInstallation, CiRun, CiTarget } from '@devdigest/shared';
import type { CiInstallationRow, CiRunRow } from '../../db/rows.js';
import type { CiRunWithMeta } from './repository.js';

/**
 * Pure helpers for the CI module — no I/O. Validation (AC-15), slug derivation
 * (manifest/skill filenames, AC-3/AC-17), and DB row -> DTO mapping.
 */

/**
 * Strict `owner/name` shape (AC-15). Each segment must start/end with an
 * alphanumeric character; the middle may contain `.`, `_`, `-`. Rejects
 * empty input, path traversal (`../evil`), and shell-metacharacter payloads
 * (`;`, `|`, `$`, backticks, whitespace, quotes — none are in the allowed set).
 */
const REPO_SLUG_RE =
  /^[a-zA-Z0-9](?:[a-zA-Z0-9._-]*[a-zA-Z0-9])?\/[a-zA-Z0-9](?:[a-zA-Z0-9._-]*[a-zA-Z0-9])?$/;

export function isValidRepoSlug(repo: string): boolean {
  return REPO_SLUG_RE.test(repo);
}

/**
 * Lowercase, ASCII, dash-separated slug for filenames
 * (`.devdigest/agents/<slug>.yaml`, `.devdigest/skills/<slug>.md`). Falls back
 * to `'agent'` / `'skill'` when the name has no sluggable characters at all
 * (e.g. an emoji-only name) so a filename is never empty.
 */
export function slugify(name: string, fallback = 'agent'): string {
  const slug = name
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[̀-ͯ]/g, '') // strip diacritics
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
  return slug || fallback;
}

/** The PR body opened for the `devdigest/ci` integration branch (AC-7). */
export function exportPrBody(agentName: string, input: CiExportInput): string {
  return [
    `This PR installs the **${agentName}** DevDigest agent as an automated PR reviewer.`,
    '',
    `- Triggers: ${input.triggers.join(', ') || '(none)'}`,
    `- Post results as: \`${input.post_as}\``,
    '',
    "_Generated by DevDigest's Export to CI wizard. Files under `.devdigest/` and the workflow",
    'are safe to review and edit like any other PR before merging._',
  ].join('\n');
}

export function toInstallationDto(row: CiInstallationRow): CiInstallation {
  return {
    id: row.id,
    agent_id: row.agentId,
    repo: row.repo,
    target_type: row.targetType as CiTarget,
    installed_at: row.installedAt.toISOString(),
  };
}

/**
 * `repo` isn't in the base `CiRun` contract yet (adding it there means
 * touching `vendor/shared/contracts/eval-ci.ts`, which is a separate sync
 * step between server and client) — extended locally so `getRunsForWorkspace`
 * can surface the CI Runs page's Repository column without a vendor edit.
 * `agent`/`duration_s` are already `.nullish()` on `CiRun` itself.
 */
export type CiRunDto = CiRun & { repo?: string | null };

export function toRunDto(row: CiRunRow | CiRunWithMeta): CiRunDto {
  return {
    id: row.id,
    ci_installation_id: row.ciInstallationId,
    pr_number: row.prNumber,
    ran_at: row.ranAt ? row.ranAt.toISOString() : null,
    status: row.status,
    findings_count: row.findingsCount,
    cost_usd: row.costUsd,
    github_url: row.githubUrl,
    source: row.source,
    ...('repo' in row ? { repo: row.repo } : {}),
    ...('agentName' in row ? { agent: row.agentName } : {}),
  };
}
