import type React from "react";

/** Co-located styles for BlastRadiusCard (Overview card matching the mockup). */
export const s: Record<string, React.CSSProperties> = {
  countsRow: {
    display: "flex",
    alignItems: "center",
    flexWrap: "wrap",
    gap: 16,
    marginBottom: 14,
    fontSize: 13,
    color: "var(--text-secondary)",
  },
  count: { display: "inline-flex", alignItems: "center", gap: 6 },
  countNum: { fontWeight: 700, color: "var(--text-primary)" },
  banner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 12px",
    borderRadius: 8,
    border: "1px solid #b4881f",
    background: "rgba(180,136,31,0.10)",
    color: "var(--text-secondary)",
    fontSize: 13,
    marginBottom: 14,
  },
  summary: { fontSize: 13, lineHeight: 1.55, color: "var(--text-secondary)", marginBottom: 14 },
  tree: { display: "flex", flexDirection: "column" },
  symbolRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    padding: "8px 6px",
    borderRadius: 6,
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-primary)",
  },
  symbolName: { fontSize: 13.5, fontWeight: 700, fontFamily: "var(--font-mono, monospace)" },
  symbolCount: { marginLeft: "auto", fontSize: 12, color: "var(--text-muted)" },
  symbolBody: { display: "flex", flexDirection: "column", gap: 6, padding: "2px 0 12px 26px" },
  callerRow: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 13 },
  arrow: { color: "var(--text-muted)" },
  badgeRow: { display: "flex", flexWrap: "wrap", gap: 6, marginTop: 4 },
  emptyBody: { fontSize: 13, color: "var(--text-muted)", paddingLeft: 26 },
  toggle: {
    marginLeft: "auto",
    display: "inline-flex",
    border: "1px solid var(--border)",
    borderRadius: 8,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  },
  toggleBtn: {
    background: "none",
    border: "none",
    padding: "4px 12px",
    fontSize: 12.5,
    fontWeight: 600,
    cursor: "pointer",
    color: "var(--text-muted)",
  },
  toggleBtnActive: {
    background: "var(--bg-input, rgba(127,127,127,0.14))",
    color: "var(--text-primary)",
  },
  prior: {
    marginTop: 16,
    paddingTop: 14,
    borderTop: "1px solid var(--border-subtle, rgba(127,127,127,0.16))",
  },
  priorHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    background: "none",
    border: "none",
    padding: "4px 2px",
    cursor: "pointer",
    textAlign: "left",
    color: "var(--text-secondary)",
    fontSize: 13,
  },
  priorCount: {
    marginLeft: "auto",
    fontSize: 12,
    color: "var(--text-muted)",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
  },
  priorItem: { display: "flex", flexDirection: "column", gap: 2, padding: "8px 2px 8px 24px" },
  priorTitle: { display: "flex", alignItems: "baseline", gap: 8, fontSize: 13 },
  priorMeta: { fontSize: 12, color: "var(--text-muted)" },
};
