import type { CSSProperties } from "react";

export const s = {
  page: {
    padding: "24px 32px 56px",
    maxWidth: 1100,
    margin: "0 auto",
  } satisfies CSSProperties,
  body: {
    display: "flex",
    gap: 32,
  } satisfies CSSProperties,
  main: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  header: {
    display: "flex",
    alignItems: "flex-start",
    gap: 14,
    marginBottom: 8,
    flexWrap: "wrap" as const,
  } satisfies CSSProperties,
  headerText: { flex: 1, minWidth: 220 } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em" } satisfies CSSProperties,
  subtitle: {
    fontSize: 13,
    color: "var(--text-secondary)",
    marginTop: 4,
  } satisfies CSSProperties,
  headerActions: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexShrink: 0,
  } satisfies CSSProperties,
  degradedBanner: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "8px 14px",
    borderRadius: 8,
    background: "var(--warn-bg, rgba(201,150,47,0.12))",
    border: "1px solid var(--border)",
    color: "var(--warn, #c9962f)",
    fontSize: 12.5,
    marginBottom: 20,
  } satisfies CSSProperties,
  aside: {
    width: 200,
    flexShrink: 0,
    position: "sticky" as const,
    top: 24,
    alignSelf: "flex-start",
  } satisfies CSSProperties,
  asideTitle: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.08em",
    textTransform: "uppercase" as const,
    color: "var(--text-muted)",
    marginBottom: 10,
  } satisfies CSSProperties,
  asideNav: {
    display: "flex",
    flexDirection: "column" as const,
    gap: 6,
  } satisfies CSSProperties,
  asideLink: {
    fontSize: 13,
    color: "var(--text-secondary)",
    textDecoration: "none",
    padding: "4px 0",
  } satisfies CSSProperties,
  section: {
    marginBottom: 16,
    scrollMarginTop: 24,
  } satisfies CSSProperties,
  sectionHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    cursor: "pointer",
    userSelect: "none" as const,
    padding: "14px var(--card-pad, 18px)",
  } satisfies CSSProperties,
  sectionTitle: { fontSize: 14, fontWeight: 700, flex: 1 } satisfies CSSProperties,
  sectionBody: { padding: "0 var(--card-pad, 18px) 18px" } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 0",
    borderTop: "1px solid var(--border)",
  } satisfies CSSProperties,
  rowFirst: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "8px 0",
  } satisfies CSSProperties,
  rowNum: {
    fontSize: 12,
    color: "var(--text-muted)",
    minWidth: 18,
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  rowMain: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowNote: { fontSize: 12.5, color: "var(--text-muted)", marginTop: 2 } satisfies CSSProperties,
  cardsGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(220px, 1fr))",
    gap: 12,
  } satisfies CSSProperties,
  taskCard: {
    padding: 14,
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface, var(--bg-elevated))",
  } satisfies CSSProperties,
  taskTitle: { fontSize: 13.5, fontWeight: 600, marginBottom: 6 } satisfies CSSProperties,
  taskPath: {
    fontSize: 12,
    color: "var(--text-secondary)",
    marginBottom: 8,
    wordBreak: "break-all" as const,
  } satisfies CSSProperties,
} as const;
