import type { CSSProperties } from "react";

export const s = {
  page: {
    padding: "28px 32px 60px",
    maxWidth: 720,
    margin: "0 auto",
    display: "flex",
    flexDirection: "column",
    gap: 28,
  } satisfies CSSProperties,
  h1: { fontSize: 24, fontWeight: 700, letterSpacing: "-0.02em", margin: 0 } satisfies CSSProperties,
  subtitle: { fontSize: 14, color: "var(--text-secondary)", margin: "6px 0 0", lineHeight: 1.5 } satisfies CSSProperties,
  stepHeader: { display: "flex", alignItems: "center", gap: 10, marginBottom: 14 } satisfies CSSProperties,
  stepBadge: {
    width: 22,
    height: 22,
    borderRadius: 99,
    background: "var(--accent-bg)",
    color: "var(--accent)",
    display: "grid",
    placeItems: "center",
    fontSize: 12,
    fontWeight: 700,
    flexShrink: 0,
  } satisfies CSSProperties,
  stepLabel: { fontSize: 15, fontWeight: 600 } satisfies CSSProperties,
  selectAll: {
    marginLeft: "auto",
    background: "none",
    border: "none",
    padding: 0,
    fontSize: 13,
    fontWeight: 600,
    color: "var(--accent-text)",
    cursor: "pointer",
  } satisfies CSSProperties,
  emptyBox: {
    border: "1px dashed var(--border-strong)",
    borderRadius: 10,
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  rows: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: (checked: boolean): CSSProperties => ({
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 9,
    border: "1px solid " + (checked ? "var(--border-strong)" : "var(--border)"),
    background: checked ? "var(--bg-hover)" : "var(--bg-elevated)",
    cursor: "pointer",
  }),
  rowInfo: { flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowName: { fontSize: 14, fontWeight: 600 } satisfies CSSProperties,
  rowDesc: {
    fontSize: 12,
    color: "var(--text-muted)",
    marginTop: 2,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowHint: { fontSize: 12, color: "var(--text-muted)", flexShrink: 0 } satisfies CSSProperties,
  footer: { display: "flex", alignItems: "center", gap: 14 } satisfies CSSProperties,
  summary: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
};
